mobile_base_controller:
  type: "diff_drive_controller/DiffDriveController"
  left_wheel: ['front_left_wheel','rear_left_wheel']
  right_wheel: ['front_right_wheel','rear_right_wheel']
  pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
  twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]

  wheel_separation : 0.45
  wheel_radius : 0.155