footprint: [[-0.41, -0.31], [-0.41, 0.31], [0.41, 0.31], [0.55, 0.0], [0.41, -0.31]]
footprint_padding: 0.03

robot_base_frame: base_link
update_frequency: 2   # estava a 4
publish_frequency: 5
transform_tolerance: 0.5

resolution: 0.05

obstacle_range: 5.5
raytrace_range: 6.0


#layer definitions
static:
    map_topic: /odom   #estava a map
    subscribe_to_updates: true

obstacles_laser:
    observation_sources: laser
    laser: {data_type: LaserScan, clearing: true, marking: true, topic: scan, inf_is_valid: true}

# obstacles_cloud:
#     observation_sources: pointcloud_sensor
#     pointcloud_sensor: {data_type: PointCloud2, topic: /camera/depth_registered/points,
#      marking: true, clearing: true, min_obstacle_height: 0.5}   

inflation:
    inflation_radius: 0.5

